(use-package projectile
  :diminish projectile-mode
  :config
  (progn
    (projectile-global-mode +1)
    ;; (setq projectile-indexing-method 'native)
    (setq projectile-enable-caching t)
    (setq projectile-completion-system 'ivy)
    (add-to-list 'projectile-other-file-alist '("js" "hbs"))
    (add-to-list 'projectile-other-file-alist '("hbs" "js"))
    ;; (setq projectile-switch-project-action 'projectile-dired)
    ))

(define-key global-map (kbd "C-c .") 'hydra-projectile/body)
(setq projectile-keymap-prefix nil)

(defhydra hydra-projectile (:color teal
                             :columns 4)
  "Projectile"
  ("4 a"    projectile-find-other-file-other-window                 "Find other window")
  ("4 b"    projectile-switch-to-buffer-other-window                 "Switch to buffer other window")
  ;; ("4 C-o"  projectile-display-buffer)
  ;; ("4 d"    projectile-find-dir-other-window)
  ;; ("4 D" projectile-dired-other-window)
  ;; ("4 f" projectile-find-file-other-window)
  ;; ("4 g" projectile-find-file-dwim-other-window)
  ;; ("4 t" projectile-find-implementation-or-test-other-window)
  ;; ("5 a" projectile-find-other-file-other-frame)
  ;; ("5 b" projectile-switch-to-buffer-other-frame)
  ;; ("5 d" projectile-find-dir-other-frame)
  ;; ("5 D" projectile-dired-other-frame)
  ;; ("5 f" projectile-find-file-other-frame)
  ;; ("5 g" projectile-find-file-dwim-other-frame)
  ;; ("5 t" projectile-find-implementation-or-test-other-frame)
  ;; ("!" projectile-run-shell-command-in-root)
  ;; ("&" projectile-run-async-shell-command-in-root)
  ;; ("a" projectile-find-other-file)
  ;; ("b" projectile-switch-to-buffer)
  ;; ("C" projectile-configure-project)
  ;; ("c" projectile-compile-project)
  ;; ("d" projectile-find-dir)
  ;; ("D" projectile-dired)
  ;; ("e" projectile-recentf)
  ;; ("E" projectile-edit-dir-locals)
  ;; ("f" projectile-find-file)
  ;; ("g" projectile-find-file-dwim)
  ;; ("F" projectile-find-file-in-known-projects)
  ;; ("i" projectile-invalidate-cache)
  ;; ("I" projectile-ibuffer)
  ;; ("j" projectile-find-tag)
  ;; ("k" projectile-kill-buffers)
  ;; ("l" projectile-find-file-in-directory)
  ;; ("m" projectile-commander)
  ;; ("o" projectile-multi-occur)
  ;; ("p" projectile-switch-project)
  ;; ("q" projectile-switch-open-project)
  ;; ("P" projectile-test-project)
  ;; ("r" projectile-replace)
  ;; ("R" projectile-regenerate-tags)
  ;; ("s g" projectile-grep)
  ;; ("s s" projectile-ag)
  ;; ("S" projectile-save-project-buffers)
  ;; ("t" projectile-toggle-between-implementation-and-test)
  ;; ("T" projectile-find-test-file)
  ;; ("u" projectile-run-project)
  ;; ("v" projectile-vc)
  ;; ("V" projectile-browse-dirty-projects)
  ;; ("x e" projectile-run-eshell)
  ;; ("x t" projectile-run-term)
  ;; ("x s" projectile-run-shell)
  ;; ("z" projectile-cache-current-file)
  ;; (ESC projectile-project-buffers-other-buffer)
  ("q"   nil "Cancel" :color blue))
