(add-to-list 'load-path "~/.emacs.d/manual/emacs-redmine")
(require 'redmine)

(defun redmine-solmates ()
  (interactive)
  (setq redmine-program "~/.emacs.d/manual/emacs-redmine/redmine.py")
  (setq redmine-project-name "solmates")
  (setq redmine-login-key "e1e1419c22432fdb3144b72b8ef5872c9c8430ce")
  (setq redmine-url "http://www.hostedredmine.com/")
  (redmine-show-sprints))
