(add-to-list 'load-path "~/.emacs.d/manual/emacs-redmine")
(require 'redmine)

(defun redmine-solmates ()
  (interactive)
  (setq redmine-program "~/.emacs.d/manual/emacs-redmine/redmine.py")
  (setq redmine-project-name "solmates")
  (setq redmine-login-key "ddbc1a5e78c1e933f2972074d92931826e21badd")
  (setq redmine-url "http://www.hostedredmine.com/")
  ;; (redmine-show-sprints)
  )
